### ISSUE TITLE
minimum sdk

### ISSUE THREAD

**Issue by mbasa** [4Q-s-r-o/call_log#1]
Is there a way to lower the minimum sdk requirement. I am getting this error:
  
```uses-sdk:minSdkVersion 16 cannot be smaller than version 23 declared in library [:call_log] /Users/mbasa/Development/AndroidStudioProjects/flutter_todai_survey/build/call_log/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 16```

**Comment by ethael** [comment]
hello. we will check this this week hopefully.

**Comment by MartinHlavna** [comment]
This will be published as version 2.0.0 along with migration to ```androidx``` from deprecated ```android.support``` packages. However we have not tested it on a real device with API level 16. It should be ok as per android documentation. 

If you find any problems with level 16 devices, please feel free to fill issue or PR. Thanks.
