### ISSUE TITLE
error, Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference, null

### ISSUE THREAD

**Issue by santoshakil** [4Q-s-r-o/call_log#11]
I'm able to get CallLog in Foreground with the call_log pub package. But I need to get Call Log in Background.

Here is some neccesery part of my code:

```
void main() {
  runApp(MaterialApp(
    home: Home(),
  ));

  Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
  Workmanager.registerPeriodicTask("1", "simplePeriodicTask",
      existingWorkPolicy: ExistingWorkPolicy.replace,
      frequency: Duration(minutes: 15),
      initialDelay:
          Duration(seconds: 5),
      constraints: Constraints(
        networkType: NetworkType.connected,
      ));
}

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async{
    await _HomeState().callLogDbManager();
    print('Background Services are Working!');
    return Future.value(true);
  });
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Future<void> callLogDbManager() async {
    Iterable<CallLogEntry> cLog = await CallLog.get();
    int rowCount = await DatabaseHelper.instance.queryRowCount();
    int clLength = cLog.length;
    if (rowCount >= clLength) {
      callLogDbUpdate();
    } else {
      await callLogDbInsert();
      callLogDbUpdate();
    }
  }
  .......
  .......
}
```

And this is the Error during getting call log in Background:

![Screenshot_20200722_233905](https://user-images.githubusercontent.com/22114787/88271713-64e6ed00-ccf9-11ea-8bb5-da0281857a13.png)

**error, Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference, null**

**Comment by l0rd0fsecrets** [comment]
I still have the same problem

**Comment by hesty** [comment]
I have the same problem

**Comment by adsizmusa** [comment]
I still have the this problem. I want to run on background

**Comment by hesty** [comment]
> I still have the this problem. I want to run on background

I found the solution.

first step - delete call_log  and work manager 

second step 
install https://pub.dev/packages/flutter_background_service
install https://pub.dev/packages/pit_sms_call_log

enjoy 💯

**Comment by MartinHlavna** [comment]
Background execution support added in 2.2.0
