### ISSUE TITLE
Accepting DateTime objects

### ISSUE THREAD

**Issue by Shadawn** [4Q-s-r-o/call_log#19]
Is it within the scope of the package to make dateFrom/dateTo to accept DateTime objects directly, so people would write less millisecondsSinceEpoch (we're still accepting integers too)? I could implement the changes if so.

**Comment by MartinHlavna** [comment]
Hi, the next version will have this as it simple nice syntactic sugar.

**Comment by MartinHlavna** [comment]
Released in 3.1.0
