### ISSUE TITLE
Getting deprecated API error while building release apk

### ISSUE THREAD

**Issue by varunkudalkar** [4Q-s-r-o/call_log#21]
While building apk I am getting the following error on the console,

`Note: /Users/.../FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/call_log-3.0.3/android/src/main/java/sk/fourq/calllog/CallLogPlugin.java uses or overrides a deprecated API.
`

although the app builds successfully also I can run the app on the device.

**Comment by ethael** [comment]
this is not an error, but a warning regarding using API that was already deprecated. You can safely use it for now. We are continuously migrating from deprecated APIs if possible.

**Comment by MartinHlavna** [comment]
Just a note - with version 3.2.0 this is just because of backwards compatibility with flutter embedding v1.
