### ISSUE TITLE
Not working on Android 6.0.1

### ISSUE THREAD

**Issue by AR553** [4Q-s-r-o/call_log#23]
Everything works great on the above android versions but throws platform exception when I query logs in android 6.0.1 (Nexus 5).

Code: 
          int from = DateTime(date.year, date.month, date.day, 0).millisecondsSinceEpoch;
          int to = DateTime(date.year, date.month, date.day, 24).millisecondsSinceEpoch;
          List<LogEntryEntity> _logs = [];
          logs = await CL.CallLog.query(dateFrom: from, dateTo: to, type: CallType.incoming);

Logs: 
E/flutter ( 5842): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(INTERNAL_ERROR, Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference, null, null)
E/flutter ( 5842): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter ( 5842): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 5842): <asynchronous suspension>
E/flutter ( 5842): #2      CallLog.query (package:call_log/call_log.dart:54:9)
E/flutter ( 5842): <asynchronous suspension>
E/flutter ( 5842): #3      LogEntity.query (package:broadcast_receiver/models/log_entity.dart:35:14)
E/flutter ( 5842): <asynchronous suspension>
E/flutter ( 5842): #4      HomeController.updateLogs (package:broadcast_receiver/controllers/home.dart:73:5)
E/flutter ( 5842): <asynchronous suspension>
E/flutter ( 5842): #5      HomeController.updateSelectedDate (package:broadcast_receiver/controllers/home.dart:94:7)
E/flutter ( 5842): <asynchronous suspension>
E/flutter ( 5842): #6      DatePicker.build.<anonymous closure> (package:broadcast_receiver/views/custom_widgets/date_picker.dart:17:9)
E/flutter ( 5842): <asynchronous suspension>
E/flutter ( 5842):

**Comment by EgHubs** [comment]
Same here on Android 8.0
any news?

**Comment by EgHubs** [comment]
I just realized that that error only occurs when there is an output that should be getting from the logs
if I put maybe a number that I don't have in the logs it gives me no error and the output indicates that there are no logs for that.
I hope that helps to solve the problem

**Comment by EgHubs** [comment]
This package is not supported anymore and not working for me.
after searching along I found this package from the [flutter plugin][1]
and I made my own [fork][2] and migrated it to null safety and it's now working
check it out as a working alternative


  [1]: https://github.com/google/flutter.plugins/tree/master/packages/phone_log
  [2]: https://github.com/EgHubs/phone_log

**Comment by ethael** [comment]
Not sure what is your problem @EgHubs, but you are lying, as you were lying in the email you have sent to us.
This package is still supported. We support it on regular basis 5-6 times. We do it for free and therefore it is not our priority to do so on demand. You wrote us a direct email and I have replied to you, that we will look into it in our next maintenance window.

And after several hours you wrote here a comment, that this package is not supported anymore and you guide people to the fork of unmaintained package, which you migrated to null safety. If you would, put this effort to creating a well written and  tested PR, this may have been already fixed. If you are not willing to contribute, at least please don't lie and put people into false assumptions. Thank you.

**Comment by EgHubs** [comment]
First, me telling people that is not supported is for a reason, there are issues here since Feb/2021 and the last reply from your side was on 4/Feb/2021 which is from 5 months, which is I think it's a long way enough for me to say that.
Second. I haven't received any reply at all from you,
nothing in my email list so I guess you are the one that is lying!

**Comment by ethael** [comment]
That's ridiculous. Maybe you should check your spam folder as gmail tends to drop many valid email domains just because they are not global email services. We supported several people via email too. But I won't spent my time here anymore. Enjoy using your phone_log fork. Have a nice day :)

**Comment by EgHubs** [comment]
and should I check my spam folder!?
it's not my mistake that you're domain is not a "global email services"
I think I shouldn't 
I will do enjoy it thanks.

**Comment by MartinHlavna** [comment]
Fix is publushed in version 3.1.0
