### ISSUE TITLE
Migrate plugin to Android embedding V2

### ISSUE THREAD

**Issue by koenniem** [4Q-s-r-o/call_log#25]
To avoid unexpected runtime failures, or future build failures, this plugin must be upgraded to Android embedding V2. Otherwise, a future release of Flutter will remove these deprecated APIs.

https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by csgulati09** [comment]
Please do the migrations

**Comment by ethael** [comment]
We will migrate this week

**Comment by holy-dev** [comment]
@ethael thanks

**Comment by MartinHlavna** [comment]
Released as 3.2.0
