### ISSUE TITLE
Not save number is not fetch

### ISSUE THREAD

**Issue by vitulgoyani** [4Q-s-r-o/call_log#4]
hay, thank you for this plugin but it does not fetch unsave number, so how can i fetch all number save and unsave also

**Comment by laravelian** [comment]
I forked the repo and fixed the issue here: https://github.com/laravelian/call_log

**Comment by MartinHlavna** [comment]
Hi @laravelian, would you mind opening PR with your fix?

**Comment by MartinHlavna** [comment]
Closed by mistake :)

**Comment by MartinHlavna** [comment]
Fixed by #7
