### ISSUE TITLE
How to get photoURI ?

### ISSUE THREAD

**Issue by KartavyaBagga** [4Q-s-r-o/call_log#41]
i thought phoneAccountID is associated contact ID with the log
![image](https://user-images.githubusercontent.com/66277203/227734034-858f1a84-43c2-4359-85f7-5158698c210d.png)

**Comment by MartinHlavna** [comment]
Account id is related to phone owner not contact and should have reason in multi sim setups. Looks like contact needs to be queried separately by phone number, shich is not something we want to do for all rows because of performance reasons. 

Maybe separate call would work in your case?

**Comment by MartinHlavna** [comment]
Maybe some king of cache in your code could work.

**Comment by MartinHlavna** [comment]
Closing for now.
