### ISSUE TITLE
Error permissions

### ISSUE THREAD

**Issue by scarrillomovatec** [4Q-s-r-o/call_log#44]
I have this log:

`D/flutter/CALL_LOG( 1232): onMethodCall
V/MiuiFrameworkFactory( 1232): get AllImpl object = android.common.MiuiFrameworkFactoryImpl@4e61412
W/MirrorManager( 1232): this model don't Support
3
D/flutter/CALL_LOG( 1232): onMethodCall
W/Activity( 1232): Can request only one set of permissions at a time
E/MethodChannel#sk.fourq.call_log( 1232): Failed to handle method call
E/MethodChannel#sk.fourq.call_log( 1232): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#sk.fourq.call_log( 1232): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/MethodChannel#sk.fourq.call_log( 1232): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:268)
E/MethodChannel#sk.fourq.call_log( 1232): 	at sk.fourq.calllog.CallLogPlugin.queryLogs(CallLogPlugin.java:234)
E/MethodChannel#sk.fourq.call_log( 1232): 	at sk.fourq.calllog.CallLogPlugin.handleMethodCall(CallLogPlugin.java:189)
E/MethodChannel#sk.fourq.call_log( 1232): 	at sk.fourq.calllog.CallLogPlugin.onRequestPermissionsResult(CallLogPlugin.java:144)
E/MethodChannel#sk.fourq.call_log( 1232): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:781)
E/MethodChannel#sk.fourq.call_log( 1232): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:413)
E/MethodChannel#sk.fourq.call_log( 1232): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:820)
E/MethodChannel#sk.fourq.call_log( 1232): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:941)
E/MethodChannel#sk.fourq.call_log( 1232): 	at android.app.Activity.requestPermissions(Activity.java:5338)
E/MethodChannel#sk.fourq.call_log( 1232): 	at androidx.core.app.ActivityCompat$Api23Impl.requestPermissions(ActivityCompat.java:893)
E/MethodChannel#sk.fourq.call_log( 1232): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:557)
E/MethodChannel#sk.fourq.call_log( 1232): 	at sk.fourq.calllog.CallLogPlugin.onMethodCall(CallLogPlugin.java:127)
E/MethodChannel#sk.fourq.call_log( 1232): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)`

**Comment by MartinHlavna** [comment]
Hello, can you please provide reproduction manual? What is your flutter version?

**Comment by MartinHlavna** [comment]
Closing as we cannot work on this without further information.
