### ISSUE TITLE
The newest entries are null

### ISSUE THREAD

**Issue by mikeon** [4Q-s-r-o/call_log#5]
Hi, strange issue, only first three call entries show null numbers. Did you hit this issue before?

**Comment by vitulgoyani** [comment]
I also fetch this issue, but when I open default recent call log and then back to app its show me all data, what is the issue I don't understand

**Comment by mikeon** [comment]
> I also fetch this issue, but when I open default recent call log and then back to app its show me all data, what is the issue I don't understand

I've was manage to fix this issue on the other lib:

https://github.com/jiajiabingcheng/phone_log/issues/2#issuecomment-504694622

**Comment by MartinHlavna** [comment]
Fixed in 2.0.1.
