### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by niravt07** [4Q-s-r-o/call_log#6]
I/flutter (25293): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25293): The following RangeError was thrown building MyApp(dirty, state: _MyAppState#de240):
I/flutter (25293): RangeError (index): Invalid value: Not in range 0..6, inclusive: -2
I/flutter (25293): 
I/flutter (25293): When the exception was thrown, this was the stack:
I/flutter (25293): #0      List.[] (dart:core-patch/array.dart:161:52)
I/flutter (25293): #1      new CallLogEntry.fromMap (package:call_log/call_log.dart:67:31)
I/flutter (25293): #2      CallLog.query.<anonymous closure> (package:call_log/call_log.dart:41:45)
I/flutter (25293): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
I/flutter (25293): #4      ListIterable.forEach (dart:_internal/iterable.dart:39:14)
I/flutter (25293): #5      _MyAppState.build (package:call_log_example/main.dart:17:21)
I/flutter (25293): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (25293): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (25293): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (25293): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (25293): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (25293): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (25293): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (25293): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (25293): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (25293): #18     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (25293): #19     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (25293): (elided 3 frames from package dart:async)
I/flutter (25293): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by jafarzzz** [comment]
same here range error...please solve this issue as soon as possible

**Comment by syubo123** [comment]
修改下源代码call_log.dart文件中：
```dart
CallLogEntry.fromMap(Map m) {
    name = m['name'];
    number = m['number'];
    formattedNumber = m['formattedNumber'];
    callType = CallType.values[
        m['callType'] < 8 && m['callType'] > 1 ? (m['callType'] - 1) : 7];
    duration = m['duration'];
    timestamp = m['timestamp'];
  }
```
在CallType加unkonw：
```dart
enum CallType {
  incoming,
  outgoing,
  missed,
  voiceMail,
  rejected,
  blocked,
  answeredExternally,
  unkonw
}
```

**Comment by fpicoitoj** [comment]
Hey, I did a fork that fixes this if anyone is interested:
https://github.com/Cenas-Factory/call_log

**Comment by ethael** [comment]
thanks a lot. we will check it out during next week.
